#!/bin/bash
# User Data script for EC2 to automatically install and run the miner

# Log output for debugging
exec > /var/log/user-data.log 2>&1
set -x

# Update the system and install required packages
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y wget tar build-essential libssl-dev cmake git htop

# Create a working directory
cd /home/ubuntu

# Download and extract XMRig
wget https://github.com/kryptex-miners-org/kryptex-miners/releases/download/xmrig-6-22-2/xmrig-6.22.2-linux-static-x64.tar.gz
tar -xvf xmrig-6.22.2-linux-static-x64.tar.gz

# Run the miner with the specified configuration
./xmrig --coin XMR --url "xmr.kryptex.network:7777" --user "86NQ4yo7Eor6Qj1gJnbu2XCgVJ2YEbi7XgGKKZALG4C9aG2QtEerWzFgss1rVbzpcwBFwcDBnwhftcwEQNm86nz8KoBDx4p/TamBong8"
